### ISSUE TITLE
Index out-of-bounds error

### ISSUE THREAD

**Issue by DTV96Calibre** [DTV96Calibre/branch_predictors#2]
Initializing global.py with `initializeBPT(4)` and attempting to set an outcome with `setPrediction(False, [True, False])` results in an index error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "global.py", line 13, in setPrediction
    BPT[index] = prediction
IndexError: list assignment index out of range`

**Comment by DTV96Calibre** [comment]
Turns out initializeBPT does not persist and BPT remains [ ]
